services:
  bin-duty:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - TZ=Europe/Luxembourg
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
